"""initial

Revision ID: fdbeae364b12
Revises: 
Create Date: 2026-07-30 17:43:36.830634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbeae364b12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('fetched_at_sim_hours', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('sim_hours', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('rate_remaining', sa.Integer(), nullable=True),
    sa.Column('retry_after', sa.Integer(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('first_seen_sim_hours', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('decided_sim_hours', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('received_sim_hours', sa.Float(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('metrics_at', sa.String(), nullable=False),
    sa.Column('sim_hours', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('cache', 'live', name='sample_source'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_post_id'), 'samples', ['post_id'], unique=False)
    op.create_index('ix_samples_post_id_sim_hours', 'samples', ['post_id', 'sim_hours'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_samples_post_id_sim_hours', table_name='samples')
    op.drop_index(op.f('ix_samples_post_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_table('alerts')
    op.drop_table('posts')
    op.drop_table('request_log')
    op.drop_table('creators')
    # ### end Alembic commands ###
    # op.drop_table('samples') does not drop the Postgres enum type that
    # backed its 'source' column (confirmed against real Postgres: the type
    # is left orphaned after the table is dropped). Drop it explicitly so
    # downgrade is fully symmetric with upgrade. No-op on SQLite.
    sa.Enum('cache', 'live', name='sample_source').drop(op.get_bind(), checkfirst=True)
